/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLbanVeMayBay;

import static QLbanVeMayBay.BanVe_nguoiditheo.Tabbed;
import static QLbanVeMayBay.SearchForm.dateDi;
import Service.GheService;
import Service.ndService;
import Service.userService;
import Service.veService;
import getItem.Ghe;
import getItem.User;
import getItem.Ve;
import getItem.userNDC;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class HoaDonVe extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonVe
     */
    User user;
    userService userService;
    Ve ve, getve;
    veService veService;
    userNDC userNDC;
    ndService ndcService;
    Ghe Ghe;
    GheService GheService;

    public HoaDonVe(String email) {
        initComponents();
        setLocationRelativeTo(null);
        ve = new Ve();
        veService = new veService();

        userNDC = new userNDC();
        ndcService = new ndService();

        GheService = new GheService();
        Ghe = GheService.getGhe(1);

        userService = new userService();
        user = userService.getUser(email);

        creditRadiobutton.setSelected(true);
        PayPalRadiobutton.setEnabled(true);
        PayPalRadiobutton.setSelected(true);
        MasterCardRadiobutton.setEnabled(true);
        VisaRadiobutton.setEnabled(true);
        nhCombobox.setEnabled(false);
        stk1Text.setEditable(false);
        sdt1Text.setEditable(false);

        int index1 = listSearchForm.ds1Table.getSelectedRow();
        int index2 = listSearchForm.ds2Table.getSelectedRow();
        TableModel model1 = listSearchForm.ds1Table.getModel();
        TableModel model2 = listSearchForm.ds2Table.getModel();
        idVeLabel1.setText(model1.getValueAt(index1, 0).toString());
        lotrinhLabel1.setText(model1.getValueAt(index1, 1).toString() + " - " + model1.getValueAt(index1, 2).toString());
        datediLabel1.setText(model1.getValueAt(index1, 4).toString());
        SogheLabel1.setText(Ghe.getSoghe().toString());
        timeDiLabel1.setText(model1.getValueAt(index1, 6).toString());

        int gia2 = 0;
        if (index2 != -1) {
            dateVeLabel1.setText(model2.getValueAt(index2, 4).toString());
            timeVeLabel1.setText(model2.getValueAt(index2, 6).toString());
            idCBveLabel.setText(model2.getValueAt(index2, 0).toString());
            gia2 = (int) model2.getValueAt(index2, 8);
        }

        nameLabel1.setText(user.getHoten());
        dateLabel1.setText(user.getNgaysinh());
        diaChilabel1.setText(user.getDiachi());
        soCMlabel1.setText(user.getSoCM());

        int slNglon = (int) SearchForm.numeric1.getValue();
        int slTre = (int) SearchForm.numeric2.getValue();
        int gia1 = (int) model1.getValueAt(index1, 8);

        TTdiLabel.setText(String.valueOf(gia1 * slNglon + (gia1 / 2) * slTre));
        TTveLabel.setText(String.valueOf(gia2 * slNglon + (gia2 / 2) * slTre));
        int TongTien = gia1 * slNglon + (gia1 / 2) * slTre + gia2 * slNglon + (gia2 / 2) * slTre;
        TTlabel.setText(String.valueOf(TongTien));

    }

    private HoaDonVe() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DkCheckbox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        sdt1Text = new javax.swing.JTextField();
        stk1Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InternetjRadioButton = new javax.swing.JRadioButton();
        nhCombobox = new javax.swing.JComboBox<>();
        viDtRadiobutton = new javax.swing.JRadioButton();
        creditRadiobutton = new javax.swing.JRadioButton();
        PayPalRadiobutton = new javax.swing.JRadioButton();
        MasterCardRadiobutton = new javax.swing.JRadioButton();
        VisaRadiobutton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        KtCheckbox = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        diaChilabel1 = new javax.swing.JLabel();
        soCMlabel1 = new javax.swing.JLabel();
        idVeLabel1 = new javax.swing.JLabel();
        SogheLabel1 = new javax.swing.JLabel();
        lotrinhLabel1 = new javax.swing.JLabel();
        datediLabel1 = new javax.swing.JLabel();
        timeDiLabel1 = new javax.swing.JLabel();
        dateVeLabel1 = new javax.swing.JLabel();
        timeVeLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TTdiLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TTveLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        dateTT = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idCBveLabel = new javax.swing.JLabel();
        TTlabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hóa đơn");

        jLabel2.setText("______________________________________________________________");

        jLabel3.setText("______________________________________________________________");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại: ");

        jLabel5.setText("______________________________________________________________");

        DkCheckbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        DkCheckbox.setText("Tôi đồng ý với những điều khoản này");
        DkCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DkCheckboxActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Cash in Hand_50px.png"))); // NOI18N
        submitButton.setText("THANH TOÁN");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số tài khoản:");

        label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label.setForeground(new java.awt.Color(0, 204, 0));
        label.setText("THÀNH TIỀN:");

        sdt1Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdt1Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sdt1TextKeyPressed(evt);
            }
        });

        stk1Text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stk1Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stk1TextKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GHI NHẬN VÉ MUA");
        jLabel1.setToolTipText("");

        buttonGroup1.add(InternetjRadioButton);
        InternetjRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        InternetjRadioButton.setForeground(new java.awt.Color(255, 0, 0));
        InternetjRadioButton.setText("InternetBanking");
        InternetjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternetjRadioButtonActionPerformed(evt);
            }
        });

        nhCombobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nhCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VietinBank", "VietcomBank", "BIDV", "SacomBank", "VIBBank", "AgriBank", " " }));
        nhCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhComboboxActionPerformed(evt);
            }
        });

        buttonGroup1.add(viDtRadiobutton);
        viDtRadiobutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        viDtRadiobutton.setForeground(new java.awt.Color(255, 0, 0));
        viDtRadiobutton.setText("Ví điện tử");
        viDtRadiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viDtRadiobuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(creditRadiobutton);
        creditRadiobutton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        creditRadiobutton.setForeground(new java.awt.Color(255, 0, 0));
        creditRadiobutton.setText("CreditCard");
        creditRadiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadiobuttonActionPerformed(evt);
            }
        });

        buttonGroup2.add(PayPalRadiobutton);
        PayPalRadiobutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PayPalRadiobutton.setText("PayPal");

        buttonGroup2.add(MasterCardRadiobutton);
        MasterCardRadiobutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasterCardRadiobutton.setText("MasterCard");

        buttonGroup2.add(VisaRadiobutton);
        VisaRadiobutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VisaRadiobutton.setText("VISA");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Thông tin khách hàng");

        KtCheckbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        KtCheckbox.setText("Tội đã kiểm tra hết toàn bộ thông tin");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Họ và tên:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Ngày sinh:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Địa chỉ:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("CMND:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setText("ID CB:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("Số ghế:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("Lộ trình:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setText("Ngày đi:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setText("Thời gian:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setText("Ngày về:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setText("Thời gian:");

        nameLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        dateLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        diaChilabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        diaChilabel1.setText("jLabel19");
        diaChilabel1.setToolTipText("");

        soCMlabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        soCMlabel1.setText("jLabel19");

        idVeLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        idVeLabel1.setText("jLabel19");

        SogheLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SogheLabel1.setText("jLabel19");

        lotrinhLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lotrinhLabel1.setText("jLabel19");

        datediLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        datediLabel1.setText("jLabel19");

        timeDiLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timeDiLabel1.setText("jLabel19");

        dateVeLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        timeVeLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timeVeLabel1.setPreferredSize(new java.awt.Dimension(50, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Tổng tiền chuyến bay đi:");

        TTdiLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TTdiLabel.setText("jLabel7");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Tổng tiền chuyến bay về:");

        TTveLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TTveLabel.setText("jLabel7");

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Cancel_50px.png"))); // NOI18N
        backButton.setText("Hủy vé");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        dateTT.setDateFormatString("dd-MM-yyyy");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Ngày TT:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("ID CB về:");

        idCBveLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        TTlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TTlabel.setForeground(new java.awt.Color(0, 204, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Ok_50px.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(creditRadiobutton)
                                .addComponent(InternetjRadioButton)
                                .addComponent(viDtRadiobutton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(PayPalRadiobutton)
                                    .addGap(42, 42, 42)
                                    .addComponent(MasterCardRadiobutton)
                                    .addGap(47, 47, 47)
                                    .addComponent(VisaRadiobutton))
                                .addComponent(nhCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(stk1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdt1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label)
                                .addGap(18, 18, 18)
                                .addComponent(TTlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TTdiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(TTveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(backButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diaChilabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(idVeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(soCMlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lotrinhLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SogheLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(datediLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(timeDiLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dateVeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 119, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel19))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addGap(226, 226, 226)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(KtCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DkCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idCBveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(25, 25, 25)
                                        .addComponent(timeVeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton))))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(dateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(diaChilabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(soCMlabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(idVeLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(SogheLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lotrinhLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(datediLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(timeDiLabel1))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(dateVeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel29))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timeVeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(idCBveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(DkCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KtCheckbox))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creditRadiobutton)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PayPalRadiobutton)
                                    .addComponent(MasterCardRadiobutton)
                                    .addComponent(VisaRadiobutton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(InternetjRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(nhCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viDtRadiobutton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sdt1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stk1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TTdiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TTveLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label)
                            .addComponent(TTlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InternetjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternetjRadioButtonActionPerformed
        // TODO add your handling code here:
        PayPalRadiobutton.setEnabled(false);
        MasterCardRadiobutton.setEnabled(false);
        VisaRadiobutton.setEnabled(false);
        nhCombobox.setEnabled(true);
        stk1Text.setEditable(true);
        sdt1Text.setEditable(false);
    }//GEN-LAST:event_InternetjRadioButtonActionPerformed

    private void nhComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhComboboxActionPerformed

    private void viDtRadiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viDtRadiobuttonActionPerformed
        // TODO add your handling code here:
        PayPalRadiobutton.setEnabled(false);
        MasterCardRadiobutton.setEnabled(false);
        VisaRadiobutton.setEnabled(false);
        nhCombobox.setEnabled(false);
        stk1Text.setEditable(false);
        sdt1Text.setEditable(true);
    }//GEN-LAST:event_viDtRadiobuttonActionPerformed

    private void creditRadiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadiobuttonActionPerformed
        // TODO add your handling code here:
        PayPalRadiobutton.setEnabled(true);
        MasterCardRadiobutton.setEnabled(true);
        VisaRadiobutton.setEnabled(true);
        nhCombobox.setEnabled(false);
        stk1Text.setEditable(false);
        sdt1Text.setEditable(false);
    }//GEN-LAST:event_creditRadiobuttonActionPerformed

    private void DkCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DkCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DkCheckboxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new SearchForm(user.getEmail()).setVisible(true);
        dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if (InternetjRadioButton.isSelected() && stk1Text.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền STK", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (viDtRadiobutton.isSelected() && sdt1Text.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền số điện thoại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (DkCheckbox.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Bạn chưa đồng ý với điều khoản", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (KtCheckbox.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Nếu đã kiểm tra thông tin hãy tích vào ô", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int index1 = listSearchForm.ds1Table.getSelectedRow();
            int index2 = listSearchForm.ds2Table.getSelectedRow();
            TableModel model1 = listSearchForm.ds1Table.getModel();
            TableModel model2 = listSearchForm.ds2Table.getModel();

            ve.setAccID(user.getAccID());
            ve.setIdCB((int) model1.getValueAt(index1, 0));
            ve.setIdghe(Ghe.getIdghe());

            String ht = null;
            if (creditRadiobutton.isSelected()) {
                ht = creditRadiobutton.getText();
            } else if (InternetjRadioButton.isSelected()) {
                ht = "Internet Banking" + " - " + stk1Text.getText();
            } else {
                ht = "Vi DT" + " - " + sdt1Text.getText();
            }
            ve.setHinhthucTT(ht);

            SimpleDateFormat dfm = new SimpleDateFormat("dd-MM-yyyy");
            String ngayTT = dfm.format(dateTT.getDate());
            ve.setNgayTT(ngayTT);
            ve.setTongtien(Integer.parseInt(TTdiLabel.getText()));
            veService.addVe(ve);

            getve = veService.getVeID(user.getAccID(), Integer.parseInt(idVeLabel1.getText()));

            int slNglon = (int) SearchForm.numeric1.getValue();
            int slTre = (int) SearchForm.numeric2.getValue();
            if (slNglon + slTre >= 2) {
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(0)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText1.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton1.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText1.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox1.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(1)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText2.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton2.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText2.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox2.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(2)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText3.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton3.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText3.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox3.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(3)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText4.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton4.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText4.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox4.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(4)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText5.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton5.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText5.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox5.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(5)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText6.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton6.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText6.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox6.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(6)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText7.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton7.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText7.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox7.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(7)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText8.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton8.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText8.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox8.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(8)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText9.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton9.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText9.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox9.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
            }

            if (index2 != -1) {

                ve.setAccID(user.getAccID());
                ve.setIdCB((int) model2.getValueAt(index2, 0));
                ve.setIdghe(Ghe.getIdghe());
                ve.setHinhthucTT(ht);
                ve.setNgayTT(ngayTT);
                ve.setTongtien(Integer.parseInt(TTveLabel.getText()));
                veService.addVe(ve);

                getve = veService.getVeID(user.getAccID(), Integer.parseInt(idCBveLabel.getText()));

                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(0)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText1.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton1.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText1.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox1.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(1)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText2.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton2.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText2.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox2.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(2)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText3.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton3.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText3.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox3.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(3)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText4.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton4.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText4.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox4.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(4)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText5.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton5.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText5.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox5.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(5)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText6.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton6.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText6.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox6.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(6)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText7.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton7.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText7.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox7.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(7)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText8.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton8.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText8.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox8.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }
                if (BanVe_nguoiditheo.Tabbed.isEnabledAt(8)) {
                    String ns1 = dfm.format(BanVe_nguoiditheo.dateText9.getDate());
                    String gt = null;
                    if (BanVe_nguoiditheo.namRadioButton9.isSelected()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    userNDC.setAccID(user.getAccID());
                    userNDC.setVeID(getve.getVeID());
                    userNDC.setHoten(BanVe_nguoiditheo.nameText9.getText());
                    userNDC.setNgaysinh(ns1);
                    userNDC.setGioitinh(gt);
                    userNDC.setQuoctich(BanVe_nguoiditheo.qtComboBox9.getSelectedItem().toString());
                    ndcService.addNdc(userNDC);

                }

            }

            JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            new NewJFrame(user.getEmail()).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void sdt1TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdt1TextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            sdt1Text.setEditable(true);
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            sdt1Text.setEditable(true);
        } else {
            sdt1Text.setEditable(false);
        }
       
    }//GEN-LAST:event_sdt1TextKeyPressed

    private void stk1TextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stk1TextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            stk1Text.setEditable(true);
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            stk1Text.setEditable(true);
        } else {
            stk1Text.setEditable(false);
        }
       
    }//GEN-LAST:event_stk1TextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DkCheckbox;
    private javax.swing.JRadioButton InternetjRadioButton;
    private javax.swing.JCheckBox KtCheckbox;
    private javax.swing.JRadioButton MasterCardRadiobutton;
    private javax.swing.JRadioButton PayPalRadiobutton;
    private javax.swing.JLabel SogheLabel1;
    private javax.swing.JLabel TTdiLabel;
    private javax.swing.JLabel TTlabel;
    private javax.swing.JLabel TTveLabel;
    private javax.swing.JRadioButton VisaRadiobutton;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton creditRadiobutton;
    private javax.swing.JLabel dateLabel1;
    private com.toedter.calendar.JDateChooser dateTT;
    private javax.swing.JLabel dateVeLabel1;
    private javax.swing.JLabel datediLabel1;
    private javax.swing.JLabel diaChilabel1;
    private javax.swing.JLabel idCBveLabel;
    private javax.swing.JLabel idVeLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lotrinhLabel1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JComboBox<String> nhCombobox;
    private javax.swing.JTextField sdt1Text;
    private javax.swing.JLabel soCMlabel1;
    private javax.swing.JTextField stk1Text;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel timeDiLabel1;
    private javax.swing.JLabel timeVeLabel1;
    private javax.swing.JRadioButton viDtRadiobutton;
    // End of variables declaration//GEN-END:variables
}
