/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLbanVeMayBay;

import Service.userService;
import getItem.User;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ketnoiSQL.ketnoiSQL;

/**
 *
 * @author ASUS
 */
public class listAccount extends javax.swing.JFrame {

    /**
     * Creates new form listAccount
     */
    userService userService;
    User user;
    DefaultTableModel dfTable;

    public listAccount() {
        initComponents();
        setLocationRelativeTo(null);
        user = new User();
        userService = new userService();
        dfTable = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        accTalbe.setModel(dfTable);
        dfTable.addColumn("ID");
        dfTable.addColumn("Email");
        dfTable.addColumn("Mật khẩu");
        dfTable.addColumn("Họ tên");
        dfTable.addColumn("Số điện thoại");
        dfTable.addColumn("Số CMND");
        dfTable.addColumn("Ngày Sinh");
        dfTable.addColumn("Giới tính");
        dfTable.addColumn("quyền TK");
        dfTable.addColumn("Quốc tịch");
        dfTable.addColumn("Địa chỉ");
        setTableData(userService.getAllUser());
    }

    void setTableData(List<User> users) {
        for (User user : users) {
            dfTable.addRow(new Object[]{
                user.getAccID(),
                user.getEmail(),
                user.getMk(),
                user.getHoten(),
                user.getSdt(),
                user.getSoCM(),
                user.getNgaysinh(),
                user.getGioitinh(),
                user.getQuyentk(),
                user.getQuoctich(),
                user.getDiachi()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accTalbe = new javax.swing.JTable();
        deteleButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        soCMText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sdtText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qtText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        diachiText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateText = new com.toedter.calendar.JDateChooser();
        clearButton = new javax.swing.JButton();
        quyenComboBox = new javax.swing.JComboBox<>();
        gtComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Danh sách tài khoản ");

        accTalbe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Mật khẩu", "Họ tên", "Số điện thoại", "Số CMND", "Ngày sinh", "Giới tính", "Quyền TK", "Quốc tịch", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accTalbe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accTalbeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accTalbe);

        deteleButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deteleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Cancel_50px.png"))); // NOI18N
        deteleButton.setText("Xóa");
        deteleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteleButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Go Back_50px.png"))); // NOI18N
        backButton.setText("Quay lại");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Ok_50px.png"))); // NOI18N
        editButton.setText("Sửa");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Plus_50px.png"))); // NOI18N
        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        passText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Họ tên");

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tài khoản");

        emailText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Số CMND");

        soCMText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soCMText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                soCMTextKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày Sinh");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Số điện thoại");

        sdtText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdtText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sdtTextKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Giới tính");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quốc tịch");

        qtText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtTextKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Địa chỉ");

        diachiText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        idText.setEditable(false);
        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ID");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Quyền truy cập");

        dateText.setDateFormatString("yyyy-MM-dd");

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/black-panel-restart-system-icon - 6.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        quyenComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quyenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));

        gtComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Edit File_50px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(184, 184, 184)
                .addComponent(deteleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(171, 171, 171)
                .addComponent(addButton))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soCMText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sdtText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quyenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(22, 22, 22)
                                        .addComponent(diachiText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(clearButton)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quyenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sdtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soCMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(clearButton)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(deteleButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(qtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(diachiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(editButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accTalbeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accTalbeMouseClicked
        // TODO add your handling code here:
        int index = accTalbe.getSelectedRow();
        TableModel model = accTalbe.getModel();
        idText.setText(model.getValueAt(index, 0).toString());
        emailText.setText(model.getValueAt(index, 1).toString());
        passText.setText(model.getValueAt(index, 2).toString());
        nameText.setText(model.getValueAt(index, 3).toString());
        sdtText.setText(model.getValueAt(index, 4).toString());
        soCMText.setText(model.getValueAt(index, 5).toString());
        String st = model.getValueAt(index, 6).toString();
        try {
            dateText.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(st));
        } catch (ParseException ex) {
            Logger.getLogger(listAccount.class.getName()).log(Level.SEVERE, null, ex);
        }

        final DefaultComboBoxModel namModel = new DefaultComboBoxModel(new String[]{"Nam", "Nu"});
        final DefaultComboBoxModel nuModel = new DefaultComboBoxModel(new String[]{"Nu", "Nam"});

        String gt = model.getValueAt(index, 7).toString();
        if (gt.equals("Nam")) {
            gtComboBox.setModel(namModel);
        } else {
            gtComboBox.setModel(nuModel);
        }

        final DefaultComboBoxModel adminModel = new DefaultComboBoxModel(new String[]{"Admin", "User"});
        final DefaultComboBoxModel userModel = new DefaultComboBoxModel(new String[]{"User", "Admin"});

        String q = model.getValueAt(index, 8).toString();
        if (q.equals("Admin")) {
            quyenComboBox.setModel(adminModel);
        } else {
            quyenComboBox.setModel(userModel);
        }
        qtText.setText(model.getValueAt(index, 9).toString());
        diachiText.setText(model.getValueAt(index, 10).toString());
    }//GEN-LAST:event_accTalbeMouseClicked

    private void deteleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteleButtonActionPerformed
        // TODO add your handling code here:
        int row = accTalbe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon", "Loi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa User này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                int userID = (int) accTalbe.getValueAt(row, 0);
                userService.deleteUser(userID);
                dfTable.setRowCount(0);
                setTableData(userService.getAllUser());

            }
        }
    }//GEN-LAST:event_deteleButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:

        if (emailText.getText().equals("") || passText.getText().equals("") || nameText.getText().equals("") || soCMText.getText().equals("") || qtText.getText().equals("") || diachiText.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (sdtText.getText().length() != 10 || soCMText.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Số điện thoại và CMND phải điền đúng 10 chữ số !", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailText.getText()))) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng dạng email", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String kt = "";
            int row = accTalbe.getSelectedRow();
            int index = accTalbe.getRowCount();
            TableModel model = accTalbe.getModel();
            for (int i = 0; i <= index - 1; i++) {
                if (emailText.getText().equals(model.getValueAt(i, 1).toString()) && i != row) {
                    kt = "Đã tồn tại email";
                    break;
                }

                if (sdtText.getText().equals(model.getValueAt(i, 4).toString()) && i != row) {
                    kt = "Đã tồn tại số diện thoại";
                    break;
                }

                if (soCMText.getText().equals(model.getValueAt(i, 5).toString()) && i != row) {
                    kt = "Đã tồn tại Số CMND";
                    break;
                }

            }
            if (kt.equals("")) {
                user.setAccID(Integer.parseInt(idText.getText()));
                user.setEmail(emailText.getText());
                user.setMk(passText.getText());
                user.setHoten(nameText.getText());
                user.setSdt(sdtText.getText());
                user.setSoCM(soCMText.getText());
                SimpleDateFormat dfm = new SimpleDateFormat("dd-MM-yyyy");
                user.setNgaysinh(dfm.format(dateText.getDate()));
                user.setGioitinh(gtComboBox.getSelectedItem().toString());
                user.setQuyentk(quyenComboBox.getSelectedItem().toString());
                user.setQuoctich(qtText.getText());
                user.setDiachi(diachiText.getText());

                userService.updateUser(user);
                dfTable.setRowCount(0);
                setTableData(userService.getAllUser());

                idText.setText("");
                emailText.setText("");
                passText.setText("");
                nameText.setText("");
                sdtText.setText("");
                soCMText.setText("");
                qtText.setText("");
                diachiText.setText("");

                JOptionPane.showMessageDialog(this, "Cap nhat thanh cong", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, kt, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_editButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        mainForm main = new mainForm();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        idText.setText("");
        emailText.setText("");
        passText.setText("");
        nameText.setText("");
        sdtText.setText("");
        soCMText.setText("");
        qtText.setText("");
        diachiText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        user.setEmail(emailText.getText());
        user.setMk(passText.getText());
        user.setHoten(nameText.getText());
        user.setSoCM(soCMText.getText());
        SimpleDateFormat dfm = new SimpleDateFormat("dd-MM-yyyy");
        user.setNgaysinh(dfm.format(dateText.getDate()).toString());
        user.setSdt(sdtText.getText());
        user.setGioitinh(gtComboBox.getSelectedItem().toString());
        user.setQuyentk(quyenComboBox.getSelectedItem().toString());
        user.setQuoctich(qtText.getText());
        user.setDiachi(diachiText.getText());

        if (emailText.getText().equals("") || passText.getText().equals("") || nameText.getText().equals("") || soCMText.getText().equals("") || qtText.getText().equals("") || diachiText.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (sdtText.getText().length() != 10 || soCMText.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Số điện thoại và CMND phải điền đúng 10 chữ số !", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailText.getText()))) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng dạng email", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {

            String kt = "";
            Connection connectUser = ketnoiSQL.getConnection();
            try {
                Statement st = connectUser.createStatement();
                ResultSet rs = st.executeQuery("select * from Account");
                while (rs.next()) {
                    if (rs.getString(2).equals(user.getEmail())) {
                        kt = "Email đã tồn tại";
                        break;
                    }
                    if (rs.getString(5).equals(user.getSdt())) {
                        kt = "Số điện thoại đã tồn tại";
                        break;
                    }
                    if (rs.getString(6).equals(user.getSoCM())) {
                        kt = "Số CMND đã tồn tại";
                        break;
                    }

                }

            } catch (SQLException ex) {
                Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            userService.ktTrungDL(user, kt);
            if (kt.equals("")) {

                userService.addUser(user);
                dfTable.setRowCount(0);
                setTableData(userService.getAllUser());

                JOptionPane.showMessageDialog(this, "Thêm thành Công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, kt, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void sdtTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdtTextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            sdtText.setEditable(true);
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            sdtText.setEditable(true);
        } else {
            sdtText.setEditable(false);
        }
    }//GEN-LAST:event_sdtTextKeyPressed

    private void soCMTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soCMTextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            soCMText.setEditable(true);
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            soCMText.setEditable(true);
        } else {
            soCMText.setEditable(false);
        }
    }//GEN-LAST:event_soCMTextKeyPressed

    private void nameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            nameText.setEditable(true);
        } else {
            nameText.setEditable(false);
        }
    }//GEN-LAST:event_nameTextKeyPressed

    private void qtTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtTextKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            qtText.setEditable(true);
        } else {
            qtText.setEditable(false);
        }
    }//GEN-LAST:event_qtTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accTalbe;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private com.toedter.calendar.JDateChooser dateText;
    private javax.swing.JButton deteleButton;
    private javax.swing.JTextField diachiText;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JComboBox<String> gtComboBox;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passText;
    private javax.swing.JTextField qtText;
    private javax.swing.JComboBox<String> quyenComboBox;
    private javax.swing.JTextField sdtText;
    private javax.swing.JTextField soCMText;
    // End of variables declaration//GEN-END:variables
}
