/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLbanVeMayBay;

import static QLbanVeMayBay.dsVe.dsVeTable;
import Service.itemService;
import Service.userService;
import Service.veService;
import getItem.Item;
import getItem.User;
import getItem.Ve;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import ketnoiSQL.ketnoiSQL;

/**
 *
 * @author ASUS
 */
public class listSearchForm extends javax.swing.JFrame {

    /**
     * Creates new form listSearchForm
     */
    itemService itemService;
    Item item1, item2;
    userService userService;
    User user;
    DefaultTableModel dfTable1, dfTable2;
    Ve Ve1, Ve2;
    veService veService;

    public listSearchForm(String email, String noidi, String noiden, String ngaydi, String ngayve, String hangghe) {
        initComponents();
        setLocationRelativeTo(null);
        userService = new userService();
        user = userService.getUser(email);
        itemService = new itemService();
        veService = new veService();

        if (ngayve == null) {
            jTabbedPane2.setEnabledAt(1, false);
            item1 = itemService.getItem_one(noidi, noiden, ngaydi, hangghe);
            item2 = itemService.getItem_one(noidi, noiden, ngaydi, hangghe);
            if (item1 != null) {
                item2.setNgaydi(null);
            }
        } else {
            item1 = itemService.getItem_one(noidi, noiden, ngaydi, hangghe);
            item2 = itemService.getItem_one(noiden, noidi, ngayve, hangghe);
        }

        dfTable1 = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dfTable2 = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ds1Table.setModel(dfTable1);
        ds2Table.setModel(dfTable2);
        dfTable1.addColumn("Mã chuyến bay");
        dfTable1.addColumn("Nơi đi");
        dfTable1.addColumn("Nơi đến");
        dfTable1.addColumn("Số hành khách");
        dfTable1.addColumn("Ngày đi");
        dfTable1.addColumn("Hạng ghế ngồi");
        dfTable1.addColumn("Thời gian đi");
        dfTable1.addColumn("Thời gian đến");
        dfTable1.addColumn("Giá");
        dfTable2.addColumn("Mã chuyến bay");
        dfTable2.addColumn("Nơi đi");
        dfTable2.addColumn("Nơi đến");
        dfTable2.addColumn("Số hành khách");
        dfTable2.addColumn("Ngày đi");
        dfTable2.addColumn("Hạng ghế ngồi");
        dfTable2.addColumn("Thời gian đi");
        dfTable2.addColumn("Thời gian đến");
        dfTable2.addColumn("Giá");
        setTableData1(itemService.getItems(noidi, noiden, ngaydi, hangghe));
        setTableData2(itemService.getItems(noiden, noidi, ngayve, hangghe));
    }

    void setTableData1(List<Item> items) {

        for (Item item : items) {
            dfTable1.addRow(new Object[]{
                item.getIdCB(),
                item.getNoidi(),
                item.getNoiden(),
                item.getSoHK(),
                item.getNgaydi(),
                item.getHangghe(),
                item.getTimedi(),
                item.getTimeden(),
                item.getGia(),});
        }

    }

    void setTableData2(List<Item> items) {

        for (Item item : items) {
            dfTable2.addRow(new Object[]{
                item.getIdCB(),
                item.getNoidi(),
                item.getNoiden(),
                item.getSoHK(),
                item.getNgaydi(),
                item.getHangghe(),
                item.getTimedi(),
                item.getTimeden(),
                item.getGia(),});
        }

    }

    listSearchForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ds1Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ds2Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách chuyến bay");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Danh sách chuyến bay");

        homeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Go Back_50px.png"))); // NOI18N
        homeButton.setText("Về Trang Chủ");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Go Back_50px.png"))); // NOI18N
        backButton.setText("Quay lại");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Ok_50px.png"))); // NOI18N
        submitButton.setText("Xác nhận");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ds1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chuyến bay", "Điểm khởi hành", "Điểm đến", "Số hành khách", "Ngày đi", "Hạng ghế ngồi", "Thời gian đi", "Thời gian đến", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ds1Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds1TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ds1Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Danh sách đi", jPanel1);

        ds2Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chuyến bay", "Điểm khởi hành", "Điểm đến", "Số hành khách", "Ngày đi", "Hạng ghế ngồi", "Thời gian đi", "Thời gian đến", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ds2Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ds2TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ds2Table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Danh sách về", jPanel2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLbanVeMayBay/Edit File_50px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeButton)
                .addGap(291, 291, 291)
                .addComponent(submitButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submitButton)
                        .addComponent(homeButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        SearchForm sr = new SearchForm(user.getEmail());
        sr.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int index1 = ds1Table.getSelectedRow();
        TableModel model1 = ds1Table.getModel();
        int index2 = ds2Table.getSelectedRow();
        TableModel model2 = ds2Table.getModel();
        int idCB1 = 0;
        int idCB2 = 0;

        if (index1 == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chuyến bay đi", "Thông báo", JOptionPane.ERROR_MESSAGE);

        } else if (SearchForm.twoRadioButton.isSelected() && index2 == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chuyến bay về", "Thông báo", JOptionPane.ERROR_MESSAGE);

        } else {
            idCB1 = (int) ds1Table.getValueAt(index1, 0);
            if (index2 != -1){
                idCB2 = (int) ds2Table.getValueAt(index2, 0);
            }
            

            String kt = "";
            Connection connectUser = ketnoiSQL.getConnection();
            try {
                Statement st = connectUser.createStatement();
                ResultSet rs = st.executeQuery("Select * from ve where accID= " + user.getAccID());
                while (rs.next()) {
                    if (rs.getInt(3) == idCB1) {
                        kt = "Khách hàng đã có vé ở trên chuyến bay đi";
                        break;

                    } else if (rs.getInt(3) == idCB2) {
                        kt = "Khách hàng đã có vé ở trên chuyến bay về";
                        break;

                    }

                }

            } catch (SQLException ex) {
                Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (kt.equals("")) {
                new Banve_nguoidaidien(user.getEmail(), item1.getNoidi(), item1.getNoiden(), item1.getNgaydi(), item2.getNgaydi(), item1.getHangghe()).setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, kt, "Thông báo", JOptionPane.ERROR_MESSAGE); 
            }

        }


    }//GEN-LAST:event_submitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        new NewJFrame(user.getEmail()).setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ds1TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds1TableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ds1TableMouseClicked

    private void ds2TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ds2TableMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_ds2TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listSearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    public static javax.swing.JTable ds1Table;
    public static javax.swing.JTable ds2Table;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
